### ISSUE TITLE
how to work with peerjs-server?

### ISSUE THREAD

**Issue by HyperClockUp** [NickCis/simple-peerjs#1]
there is a peerjs server in my express application, and i set the config as 
`const WEBRTC_SERVER_CONFIG = {
  host: '127.0.0.1',
  port: 1234,
  path: "/peerjs/WebRTCLive",
  debug: 3,
}`
so i create a instance 
`const peerClient = new SimplePeerJs({
  wrtc,
  fetch,
  WebSocket,
  id: "test-host",
  simplePeer: WEBRTC_SERVER_CONFIG
})`

but nothing works, it really confuses me a lot, do u know what happened or how to deal with them?

**Comment by NickCis** [comment]
Hi!,

I'm not understanding what's the error and what are you trying to achieve.

The `simplePeer` parameter is just to set configuration for [`simple-peer`](https://github.com/feross/simple-peer), ie, the webRTC implementation, not for peerjs (the signaling handshake).

Can you explain what are you trying to do?. Also, if you can, attach the code that would work using peerjs.

**Comment by HyperClockUp** [comment]
Thanks for your reply.
My application is used for Live, so I want to establish a connection between server(NodeJS) and client (Browser), so that i can record all stream from client as media file. My solution is that make peerjs-server as server, peerjs as client. But as you know, peerjs can not  work in nodejs, that's why i create this issue.

**Comment by NickCis** [comment]
I think that you are using the incorrect tool for the problem that you are trying to solve.

If you want a persistent communication between a web client and a server, you should probably use WebSockets, not a WebRTC-like framework. PeerJs and SimplePeer (also Simple-peerjs) are peer to peer solutions. You should probably look at the [socket.io](https://socket.io/) project.

**Comment by HyperClockUp** [comment]
the alternative plan is record and upload by slice, but it will cost more time. less time delay is the reason why i choose WebRTC as first plan.
thanks
