### ISSUE TITLE
Changing the default peer server

### ISSUE THREAD

**Issue by pywrangler** [NickCis/simple-peerjs#4]
I have hosted my own peerjs server on AWS and was trying to connect to that, but unlike peerjs where I can pass that server as 'host' and 'port' while creating new Peer( { host:, port: }), this doesn't seem to work with simple-peerjs. Any solution to this, or am I missing something?

Brilliant work by the way, ur hard work is well appreciated!

**Comment by NickCis** [comment]
Hi, you should be able to pass all those options to the `SimplePeerJs` class:

```js
const SimplePeerJs = require('simple-peerjs');

const peer = new SimplePeerJs({
  host: ...,
  post: ...,
});
```
