### ISSUE TITLE
Example 'connection' typo

### ISSUE THREAD

**Issue by jabza** [NickCis/simple-peerjs#6]
This is a great library, thank you for creating it.

The example refers to a 'connection' event, but after some head scratching I found this should actually be 'connect'.
As soon as I made that change, everything just worked.

Thanks again!

**Comment by NickCis** [comment]
Hi there!, Sorry about that readme typos :sweat: . Just for the record, the examples on the [`examples` folder](https://github.com/NickCis/simple-peerjs/tree/master/exmaples) have the correct event (`connect` as you've said!).

I'm glad that you've found the project useful :). 

I have fixed the readme thanks for the notice!
